# This is a basic workflow to help you get started with Actions

name: Linux Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: XADMaster
      - uses: actions/checkout@v2
        with:
          repository: MacPaw/universal-detector
          path: UniversalDetector

      # Preinsatll libs
      - name: Install libs
        run: sudo apt-get update && sudo apt-get install --fix-missing build-essential libgnustep-base-dev libz-dev libbz2-dev libssl-dev libicu-dev libwavpack-dev

      # Runs a single command using the runners shell
      - name: Build project
        run: cd XADMaster && make -f Makefile.linux
